apiVersion: v1
kind: Template
labels:
  template: instrumented-app
metadata:
  name: instrumented-app
  labels:
    app: instrumented-app
  annotations:
    description: Intrumented App
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: instrumented-app
    name: instrumented-app
  spec:
    replicas: 1
    selector:
      app: instrumented-app
      deploymentconfig: instrumented-app
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: instrumented-app
          deploymentconfig: instrumented-app
      spec:
        containers:
        - image: jkarasek/metrics:1
          imagePullPolicy: IfNotPresent
          name: instrumented-app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    name: instrumented-app
    labels:
      app: instrumented-app
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: instrumented-app
      weight: 100
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: instrumented-app
    name: instrumented-app
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: instrumented-app
      deploymentconfig: instrumented-app
    sessionAffinity: None
    type: ClusterIP
